name: "UHF Server"
version: "1.0.0"
slug: "uhf_server"
description: "Addon wrapping solid-pixel/uhf-server"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
host_network: true
options: {}
schema: {}
ports:
  8080/tcp: 8080
