name: "UHF Server"
version: "1.0.1"
slug: "uhf_server"
description: "Addon wrapping solid-pixel/uhf-server"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
host_network: true
options:
  port: 8080
  config_file: "/config/uhf_server/config.yaml"
schema:
  port: "int(1,65535)"
  config_file: "str"
ports:
  8080/tcp: 8080
