name: "UHF Server"
version: "1.0.2"
slug: "uhf_server"
description: "Home Assistant addon wrapping solid-pixel/uhf-server-docker"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
image: "solid-pixel/uhf-server-docker:latest"
host_network: true
options:
  port: 8080
schema:
  port: "int(1,65535)"
ports:
  8080/tcp: 8080
